
spring:
  datasource:
    username: 
    password:
    url: jdbc:mysql://
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

