

spring:
  datasource:
    username: shopmaster
    password: bookspring23
    url: jdbc:mysql://shop-book.ciclmc7wjq3o.ap-northeast-2.rds.amazonaws.com:3306/shop_book
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
